name: 'Setup Android Build Environment'
description: 'Sets up Java, Android SDK, Gradle cache, and decrypts google-services.json'

inputs:
  gms-passphrase:
    description: 'Passphrase for decrypting google-services.json'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: "21"
        distribution: "temurin"

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Decrypt google-services.json
      run: |
        mkdir -p app
        openssl aes-256-cbc -d \
            -pbkdf2 \
            -iter 100000 \
            -in app/google-services.json.enc \
            -out app/google-services.json \
            -pass env:GMS_PASSPHRASE
      shell: bash

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash
