name: Android CI/CD Pipeline

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

permissions:
    contents: read
    checks: write
    pull-requests: write
    security-events: write
jobs:
    ktlint:
        name: Check Code Quality
        runs-on: ubuntu-latest

        steps:
            - name: Clone repo
              uses: actions/checkout@v4.1.1
              with:
                  fetch-depth: 1
            - name: ktlint
              uses: ScaCap/action-ktlint@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  reporter: github-pr-review # Change reporter
                  fail_on_error: true # Fail on error
    test:
        name: Unit Tests
        runs-on: ubuntu-latest
        needs: ktlint

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Android Build Environment
              uses: ./.github/actions/setup-android-build
              with:
                  gms-passphrase: ${{ secrets.GMS_PASSPHRASE }}

            - name: Run unit tests
              run: ./gradlew testDebugUnitTest

            - name: Generate test report
              uses: dorny/test-reporter@v1
              if: success() || failure()
              with:
                  name: Unit Test Results
                  path: "**/test-results/**/*.xml"
                  reporter: java-junit
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Generate coverage report
              run: ./gradlew jacocoTestReport

            - name: Comment coverage on PR
              if: github.event_name == 'pull_request'
              uses: madrapps/jacoco-report@v1.6.1
              with:
                  paths: |
                      ${{ github.workspace }}/app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
                  token: ${{ secrets.GITHUB_TOKEN }}
                  min-coverage-overall: 80
                  min-coverage-changed-files: 80
                  title: "Code Coverage Report"
                  update-comment: true

    build:
        name: Build APK
        runs-on: ubuntu-latest
        needs: test

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Android Build Environment
              uses: ./.github/actions/setup-android-build
              with:
                  gms-passphrase: ${{ secrets.GMS_PASSPHRASE }}

            - name: Build debug APK
              run: ./gradlew assembleDebug

            - name: Upload debug APK
              uses: actions/upload-artifact@v4
              with:
                  name: debug-apk
                  path: app/build/outputs/apk/debug/app-debug.apk

    security-scan:
        name: Security Scan
        runs-on: ubuntu-latest
        needs: test

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@master
              with:
                  scan-type: "fs"
                  scan-ref: "."
                  format: "sarif"
                  output: "trivy-results.sarif"

            - name: Upload Trivy scan results to GitHub Security tab
              uses: github/codeql-action/upload-sarif@v3
              if: always()
              with:
                  sarif_file: "trivy-results.sarif"
