name: ktlint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ktlint:
    name: Run ktlintCheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: >-
            ${{ runner.os }}-gradle-${{ hashFiles(
              '**/*.gradle*',
              '**/gradle-wrapper.properties'
            ) }}

      - name: ktlintCheck
        run: ./gradlew ktlintCheck
        
      - name: Annotate ktlint errors with reviewdog
        run: |
          reviewdog \
            -f=checkstyle \
            -name="ktlint" \
            -reporter=github-pr-review \
            -filter-mode=added \
            -fail-on-error=false \
            -input=build/reports/ktlint/ktlintCheckCheckstyleReport.xml
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
