name: Code Quality

on:
    pull_request:
        types: [opened, synchronize, reopened]

permissions:
    contents: read # default for checkout
    pull-requests: write # needed to post PR review comments

jobs:
    ktlint:
        name: Run ktlint
        runs-on: ubuntu-latest

        steps:
            - name: Clone repo
              uses: actions/checkout@master
              with:
                  fetch-depth: 1
            - name: Make gradlew executable
              run: chmod +x ./gradlew

            - name: Make check.sh executable
              run: chmod +x .github/scripts/check.sh

            - name: Install Review Dog
              uses: reviewdog/action-setup@v1
              with:
                  reviewdog_version: latest

            - name: Ktlint
              env:
                  REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.github_token }}
              run: |
                  ./gradlew ktlintCheck 2>&1 \
                    | grep '\.kt:' \
                    | sed 's/\([^:]*\.kt:[0-9]*:[0-9]*\) \(.*\)/\1 E: \2/' \
                    | reviewdog \
                        -name="ktlint" \
                        -reporter=github-pr-review \
                        -efm="%f:%l:%c %t: %m" \
                        -level=error \
                        -filter-mode=nofilter \
                        -fail-level=error
