name: Code Quality
on:
    pull_request:
        types: [opened, synchronize, reopened]

permissions:
    contents: read
    pull-requests: write

jobs:
    ktlint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup JDK
              uses: actions/setup-java@v3
              with:
                  distribution: temurin
                  java-version: 21

            - name: Run ktlint via reviewdog Action
              uses: ScaCap/action-ktlint@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  reporter: github-pr-review
                  filter_mode: nofilter
                  fail_on_error: true
